Documentation emoji
ahnaf-zamil/zenora pull request #29
Opened 2020-09-25 11:50 UTC by gauravndabhade

2020-09-25 14:21 UTC, ahnaf-zamil commented
I'm leaving the review to @MaksymKarunos

2020-09-25 21:51 UTC, MaksymKarunos commented on zenora/impl/rest.py
>          Delete emoji for guild
missing article

2020-09-25 22:12 UTC, MaksymKarunos commented on docs/build/html/_modules/index.html
> +<li><a href="zenora/emojis.html">zenora.emojis</a></li>
The plural form of emoji is emoji, not emojiS.

2020-09-25 22:17 UTC, MaksymKarunos commented on docs/build/html/_modules/zenora/base/factory.html
> +<span class="sd">        Parse response data from Dicord API into list of emoji objects</span>
into a list of emojis.

2020-09-25 23:00 UTC, MaksymKarunos requested changes
First of all, congratulations on your first Pull Request. We are highly appreciative of your time and efforts you put into Zenora. We are very happy to have you.

As I mentioned in the channel, the PR is really great and it has some good quality code. The only concern is that we are missing some articles and the plural of emoji is emoji, not emojis. I tried to fix it myself, but I see that I cannot make changes to the names of the files in the PR. Please see my comments, my commit where I started fixing docstrings. 
Let me know if you have any questions!

2020-09-26 03:08 UTC, ahnaf-zamil commented
I've checked the Sphinx docstrings and there are tons of grammatical errors. The PR is really good and the code is clean, but you need to have proper grammar in the docs so that the user wont have difficulty using the module

2020-09-26 05:51 UTC, gauravndabhade commented
Thanks @MaksymKarunos @ahnaf-zamil for review. I will revise the documentation and update in same PR.

2020-09-30 12:17 UTC, ahnaf-zamil commented
I'm closing this pr since there are merge conflicts

2020-09-30 12:17 UTC, closed without merging